### PR TITLE
Support font + other non image urls reffered by stylesheet

### PR DESCRIPTION
**Pull request by mfazekas**
Font url-s referred from stylesheets were not loaded.

### CODE REVIEW

**Comment by iranthau** [comment]
+1 on font urls

We also need svgs to be included in the native loader.

Is there any news on this?

**Comment by mfazekas** [comment]
@fotinakis pls review, so basically this adds the ability to load assets referred by the stylesheet vs the ones in the page. So maybe we can add an option like this:


```
use_loader(:native, include_assets_from_stylesheets: ->(path) { !(path =~ /^.+\.(png|gif)$/) } )
use_loader(:native, include_assets_from_stylesheets: :none } )
use_loader(:native, include_assets_from_stylesheets: :all } )
```

the current and default semantics would be `:none`

**Comment by mfazekas** [comment]
Pls review i think it's ready to merge. Added some simple test, removed configuration option.

**Comment by fotinakis** [comment]
Done! Released in v2.4.4

**Pull request merged**
