### PR TITLE
try automatic server number

### PR DESCRIPTION
**Pull request by joscha**
I saw some errors appearing in our builds after I enabled automatic server numbers for Xvfb

### CODE REVIEW

**Comment by joscha** [comment]
Not sure the errors are related though, will have another look to try and make sure.

**Comment by timhaines** [comment]
@joscha Well, our CI failed horribly on this PR.  Looks like it very well could be related.  Do you know more about what's going on here?

**Comment by joscha** [comment]
> Do you know more about what's going on here?

actually, I got it working on our build, so it is not the automatic server number, which is good for me, but means there are probably some other problems lurking :)

**Comment by timhaines** [comment]
@joscha Hmm. I'm going to do a fresh CI on our master branch again - just to be sure everything's good there.

**Pull request closed without merging**
